Updated codes and docker etc

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,5 +1,5 @@
 # ----- 1. First stage to build ismrmrd and siemens_to_ismrmrd -----
-FROM python:3.12.0-slim AS mrd_converter
+FROM pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime AS mrd_converter
 ARG  DEBIAN_FRONTEND=noninteractive
 ENV  TZ=America/Chicago
 
@@ -31,82 +31,63 @@ RUN cd /opt/code && \
 # Create archive of ISMRMRD libraries (including symlinks) for second stage
 RUN cd /usr/local/lib && tar -czvf libismrmrd.tar.gz libismrmrd*
 
-# ----- 2. Create a devcontainer without all of the build dependencies of MRD -----
-FROM  pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime AS python-mrd-devcontainer
+# ----- 2. Build Python environment (with CUDA compiler available) -----
+FROM pytorch/pytorch:2.3.0-cuda11.8-cudnn8-devel AS python-mrd-builder
+
+ARG DEBIAN_FRONTEND=noninteractive
+
+RUN apt-get update && apt-get install -y git build-essential libxslt1.1 libhdf5-103 libboost-program-options1.74.0 libpugixml1v5 dos2unix
+
+# Install Python packages that require CUDA to compile
+RUN pip3 install mri-nufft gpuNUFFT cufinufft finufft cupy-cuda11x \
+                 finufft scikit-image joblib git+https://github.com/mind-inria/ggrappa@openrecon nvitop && \
+    pip3 install matplotlib==3.8.2 pydicom==3.0.1 h5py==3.10.0 ismrmrd==1.14.1
+
+# Install ISMRMRD Python tools
+RUN mkdir -p /opt/code && cd /opt/code && \
+    git clone https://github.com/ismrmrd/ismrmrd-python-tools.git && \
+    cd ismrmrd-python-tools && pip3 install --no-cache-dir .
+
+# Optional cleanup
+RUN rm -rf /root/.cache/pip
+
+# ----- 3. Final runtime image -----
+FROM pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime AS python-mrd-runtime
 
 LABEL org.opencontainers.image.description="Python MRD Image Reconstruction and Analysis Server"
 LABEL org.opencontainers.image.url="https://github.com/kspaceKelvin/python-ismrmrd-server"
 LABEL org.opencontainers.image.authors="Kelvin Chow (kelvin.chow@siemens-healthineers.com)"
 
-# Copy ISMRMRD files from last stage
+# Copy ISMRMRD and siemens_to_ismrmrd binaries from stage 1
 COPY --from=mrd_converter /usr/local/include/ismrmrd        /usr/local/include/ismrmrd/
 COPY --from=mrd_converter /usr/local/share/ismrmrd          /usr/local/share/ismrmrd/
 COPY --from=mrd_converter /usr/local/bin/ismrmrd*           /usr/local/bin/
 COPY --from=mrd_converter /usr/local/lib/libismrmrd.tar.gz  /usr/local/lib/
 RUN cd /usr/local/lib && tar -zxvf libismrmrd.tar.gz && rm libismrmrd.tar.gz && ldconfig
+COPY --from=mrd_converter /usr/local/bin/siemens_to_ismrmrd /usr/local/bin/siemens_to_ismrmrd
 
-# Copy siemens_to_ismrmrd from last stage
-COPY --from=mrd_converter /usr/local/bin/siemens_to_ismrmrd  /usr/local/bin/siemens_to_ismrmrd
+# Runtime dependencies only
+RUN apt-get update && apt-get install --no-install-recommends -y \
+    libxslt1.1 libhdf5-103 libboost-program-options1.74.0 libpugixml1v5 git dos2unix nano htop && \
+    apt-get clean && rm -rf /var/lib/apt/lists/*
 
-# Add dependencies for siemens_to_ismrmrd
-RUN apt-get update && apt-get install --no-install-recommends -y libxslt1.1 libhdf5-100 libboost-program-options1.65.1 libpugixml1v5 git build-essential dos2unix nano htop
-RUN mkdir -p /opt/code
+# Copy all built Python packages from builder
+COPY --from=python-mrd-builder /opt/conda/lib/python3.10/site-packages /opt/conda/lib/python3.10/site-packages
 
-# Tell nano to remember its position from the last time it opened a file
-RUN echo "set positionlog" > ~/.nanorc
-
-RUN pip3 install mri-nufft gpuNUFFT cufinufft finufft cupy-cuda11x finufft scikit-image joblib git+https://github.com/mind-inria/ggrappa@openrecon nvitop
-
-# Python MRD library
-RUN pip3 install --no-cache-dir matplotlib==3.8.2 pydicom==3.0.1 
-
-RUN pip3 install h5py==3.10.0 ismrmrd==1.14.1
-
-RUN cd /opt/code && \
-    git clone https://github.com/ismrmrd/ismrmrd-python-tools.git && \
-    cd /opt/code/ismrmrd-python-tools && \
-    pip3 install --no-cache-dir .
-
-
-# Cleanup files not required after installation
-RUN apt-get clean && \
-    rm -rf /var/lib/apt/lists/* && \
-    rm -rf /root/.cache/pip
-
-# ----- 3. Copy deployed code into the devcontainer for deployment -----
-FROM python-mrd-devcontainer AS python-mrd-runtime
-
-# If building from the GitHub repo, uncomment the below section, open a command
-# prompt in the folder containing this Dockerfile and run the command:
-#    docker build --no-cache -t kspacekelvin/fire-python ./
-# RUN cd /opt/code && \
-#     git clone https://github.com/kspaceKelvin/python-ismrmrd-server.git
-
-# If doing local development, use this section to copy local code into Docker
-# image. From the python-ismrmrd-server folder, uncomment the following lines
-# below and run the command:
-#    docker build --no-cache -t fire-python-custom -f docker/Dockerfile ./
+# Set up workspace
 RUN mkdir -p /opt/code/python-ismrmrd-server
 COPY . /opt/code/python-ismrmrd-server
 
-# Throw an explicit error if docker build is run from the folder *containing*
-# python-ismrmrd-server instead of within it (i.e. old method)
-RUN if [ -d /opt/code/python-ismrmrd-server/python-ismrmrd-server ]; then echo "docker build should be run inside of python-ismrmrd-server instead of one directory up"; exit 1; fi
+RUN if [ -d /opt/code/python-ismrmrd-server/python-ismrmrd-server ]; then \
+    echo "docker build should be run inside of python-ismrmrd-server instead of one directory up"; exit 1; fi
 
-# Ensure startup scripts have Unix (LF) line endings, which may not be true
-# if the git repo is cloned in Windows
-RUN find /opt/code/python-ismrmrd-server -name "*.sh" | xargs dos2unix
+RUN find /opt/code/python-ismrmrd-server -name "*.sh" | xargs dos2unix && \
+    find /opt/code/python-ismrmrd-server -name "*.sh" -exec chmod +x {} \; && \
+    echo "set positionlog" > ~/.nanorc
 
-# Ensure startup scripts are marked as executable, which may be lost if files
-# are copied in Windows
-RUN find /opt/code/python-ismrmrd-server -name "*.sh" -exec chmod +x {} \;
+ENV NVIDIA_VISIBLE_DEVICES=all \
+    NVIDIA_DRIVER_CAPABILITIES=compute,utility
 
-# Set the starting directory so that code can use relative paths
 WORKDIR /opt/code/python-ismrmrd-server
+CMD ["/bin/bash", "-c", "/usr/sbin/ldconfig && exec python3 main.py -v -H=0.0.0.0 -p=9002 -l=/tmp/python-ismrmrd-server.log --defaultConfig=sparkling"]
 
-#CMD [ "python3", "/opt/code/python-ismrmrd-server/main.py", "-v", "-H=0.0.0.0", "-p=9002", "-l=/tmp/python-ismrmrd-server.log", "--defaultConfig=sparkling"]
-CMD [ "python3", "/opt/code/python-ismrmrd-server/main.py", "-v", "-H=0.0.0.0", "-p=9002", "-l=/tmp/python-ismrmrd-server.log", "--defaultConfig=sparkling"]
-
-# Replace the above CMD with this ENTRYPOINT to allow allow "docker stop"
-# commands to be passed to the server.  This is useful for deployments, but
-# more annoying for development
